using Microsoft.EntityFrameworkCore.Migrations;

namespace kompiuteriuRinkykla.Migrations
{
    public partial class DemoParts : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                "SET IDENTITY_INSERT [dbo].[Part] ON; " +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1002, N'Wastern Digital', N'Caviar Blue', N'WD10EZEX', 33, N'2019-05-25 13:45:08', N'2019-05-25 13:45:08', 1, N'SSD', NULL, NULL, 0, NULL, N'SAS 12 Gb/s', NULL, 0, 5, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, NULL, 0, 0, 1)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1003, N'Seagate', N'Barracuda', N'ST2000DM006', 59, N'2019-05-25 13:46:20', N'2019-05-25 13:46:20', 1, N'HDD', NULL, NULL, 0, NULL, N'SATA 6 Gb/s', NULL, 0, 6, 0, 0, 0, 0, 0, 2000, 0, 0, 0, 0, NULL, 0, 0, 1)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1004, N'Samsung', N'860 Eva', N'MZ76E500BW', 77, N'2019-05-25 13:47:10', N'2019-05-25 13:47:10', 1, N'SSD', NULL, NULL, 0, NULL, N'SATA 6 Gb/s', NULL, 0, 5, 0, 0, 0, 0, 0, 500, 0, 0, 0, 0, NULL, 0, 0, 1)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1005, N'Intel', N'660 P Series', N'SSDPEKNW0108X1', 109, N'2019-05-25 13:48:23', N'2019-05-25 13:48:23', 1, N'SSD', NULL, NULL, 0, NULL, N'SAS 3 Gb/s', NULL, 0, 10, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, NULL, 0, 0, 1)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1006, N'Corsair', N'Vengeance LPX', N'WDSGBD1515', 89, N'2019-05-25 13:49:31', N'2019-05-25 13:49:31', 1, N'DDR4', NULL, N'288-pin DIMM', 0, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, NULL, 0, 0, 2)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1007, N'G.Skill', N'Trident Z RGB', N'DNJKF54548DS', 114, N'2019-05-25 13:51:01', N'2019-05-25 13:51:01', 1, N'DDR4', NULL, N'288-pin DIMM', 0, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, NULL, 0, 0, 2)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1008, N'Crucial', N'CDKJHHFK8455', N'JKFDKLF5454DD', 590, N'2019-05-25 13:54:10', N'2019-05-25 13:54:10', 1, N'DDR4', NULL, N'288-pin DIMM', 0, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, NULL, 0, 0, 2)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1009, N'Kingston', N'HyperX Predator', N'JDJK54DJD', 107, N'2019-05-25 13:54:48', N'2019-05-25 13:54:48', 1, N'DDR4', NULL, N'288-pin DIMM', 0, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, NULL, 0, 0, 2)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1010, N'Intel', N'Core i9 - 9900k', N'JSKJXK455SS', 484, N'2019-05-25 13:56:20', N'2019-05-25 13:56:20', 1, NULL, NULL, N'AM4', 8, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 95, 3, NULL, 0, 0, 3)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1011, N'AMD', N'Ryzen 5 2600', N'DJS554dDD', 146, N'2019-05-25 13:57:04', N'2019-05-25 13:57:04', 1, NULL, NULL, N'AM4', 6, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 65, 3, NULL, 0, 0, 3)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1012, N'AMD', N'Ryzen 7 2700X', N'JDHJS54SJS', 279, N'2019-05-25 13:57:45', N'2019-05-25 13:57:45', 1, NULL, NULL, N'AM4', 8, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 105, 4, NULL, 0, 0, 3)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1013, N'AMD', N'Threadripper 1920X', N'JDKSLD84dH', 317, N'2019-05-25 13:58:42', N'2019-05-25 13:58:42', 1, NULL, NULL, N'AM4', 12, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 180, 4, NULL, 0, 0, 3)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1014, N'NZXT', N'H500', N'DJDJ656SSS', 69, N'2019-05-25 14:00:52', N'2019-05-25 14:00:52', 1, NULL, N'Black ', NULL, 0, NULL, NULL, NULL, 46, 42, 9, 38, 6, 10, 0, 0, 0, 0, 0, 0, NULL, 0, 21, 4)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1015, N'Cooler Master', N'MasterBox Q300', N'SJSKS5455S', 39, N'2019-05-25 14:02:41', N'2019-05-25 14:02:41', 1, NULL, N'White', NULL, 0, NULL, NULL, NULL, 47, 45, 9, 12, 7, 10, 0, 0, 0, 0, 0, 0, NULL, 0, 23, 4)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1016, N'Corsair', N'200R', N'SKKS555SJS', 59, N'2019-05-25 14:03:40', N'2019-05-25 14:03:40', 1, NULL, N'Black', NULL, 0, NULL, NULL, NULL, 55, 50, 12, 20, 6, 8, 0, 0, 0, 0, 0, 0, NULL, 0, 29, 4)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1017, N'MSI', N'B450', N'SJSJS56565', 109, N'2019-05-25 14:04:31', N'2019-05-25 14:04:31', 1, NULL, NULL, NULL, 0, N'AM4', NULL, NULL, 0, 7, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, N'288-pin DIMM', 4, 0, 5)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1018, N'Asus', N'ROG STRIX B450-F GAMMING', N'KSJSJ54454', 119, N'2019-05-25 14:05:26', N'2019-05-25 14:05:26', 1, NULL, NULL, NULL, 0, N'AM4', NULL, NULL, 0, 6, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, N'288-pin DIMM', 4, 0, 5)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1019, N'Gigabyte', N'B450M', N'SJSJD5454SSS', 65, N'2019-05-25 14:06:13', N'2019-05-25 14:06:13', 1, NULL, NULL, NULL, 0, N'AM4', NULL, NULL, 0, 7, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, N'288-pin DIMM', 4, 0, 5)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1020, N'MSI', N'MEG Z390 ACE', N'SJSK5154SJNS', 271, N'2019-05-25 14:06:54', N'2019-05-25 14:06:54', 1, NULL, NULL, NULL, 0, N'AM4', NULL, NULL, 0, 6, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, N'288-pin DIMM', 4, 0, 5)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1021, N'Gigabyte', N'WINDFORCE', N'JDNJD54D54DD', 478, N'2019-05-25 14:08:00', N'2019-05-25 14:08:00', 1, N'PCIe x16', NULL, NULL, 0, NULL, NULL, NULL, 0, 7, 0, 0, 0, 0, 0, 8, 2, 0, 130, 0, NULL, 0, 0, 6)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1022, N'MSI', N'ARMOR OC', N'SHD555SNS', 164, N'2019-05-25 14:08:40', N'2019-05-25 14:08:40', 1, N'PCIe x16', NULL, NULL, 0, NULL, NULL, NULL, 0, 7, 0, 0, 0, 0, 0, 8, 1, 0, 90, 0, NULL, 0, 0, 6)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1023, N'EVGA', N'Black', N'SJKD55SJDJ', 1059, N'2019-05-25 14:09:16', N'2019-05-25 14:09:16', 1, N'PCIe x16', NULL, NULL, 0, NULL, NULL, NULL, 0, 7, 0, 0, 0, 0, 0, 11, 4, 0, 200, 0, NULL, 0, 0, 6)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1024, N'Corsair', N'CXM', N'SJSKD5454SS', 52, N'2019-05-25 14:10:09', N'2019-05-25 14:10:09', 1, NULL, NULL, NULL, 0, NULL, NULL, N'80+ Bronze', 0, 10, 0, 0, 0, 0, 0, 0, 0, 2, 550, 0, NULL, 0, 0, 7)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1025, N'EVGA', N'SuperNOVA G3', N'SJS5545JLJLF', 104, N'2019-05-25 14:10:53', N'2019-05-25 14:10:53', 1, NULL, NULL, NULL, 0, NULL, NULL, N'80+ Gold', 0, 11, 0, 0, 0, 0, 0, 0, 0, 2, 750, 0, NULL, 0, 0, 7)" +
"INSERT INTO [dbo].[Part] ([Id], [Manufacturer], [Model], [Code], [Price], [DateCreated], [DateModified], [Qty], [Type], [Color], [ConnectionType], [CoreCount], [CpuConnType], [DataStorageInterface], [EfficiencyRating], [Height], [Length], [MaxDataStorageLength], [MaxGpuLength], [MaxMotherboardLength], [MaxPsuLength], [MaxRam], [MemoryGb], [MonitorSocketCount], [PciSocketCount], [Power], [ProcessorFrequency], [RamConnType], [RamSocketCount], [Width], [PartTypeId]) VALUES (1026, N'Corsair', N'RMX', N'MdnDMD78', 73, N'2019-05-25 14:11:33', N'2019-05-25 14:11:33', 1, NULL, NULL, NULL, 0, NULL, NULL, N'80+ Gold', 0, 9, 0, 0, 0, 0, 0, 0, 0, 2, 650, 0, NULL, 0, 0, 7)" +
"SET IDENTITY_INSERT [dbo].[Part] OFF; "
        );

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
